---
# tasks file for putty

- name: Download putty
  win_get_url:
    url: https://the.earth.li/~sgtatham/putty/latest/w64/putty-64bit-0.76-installer.msi
    dest: C:\tmp\putty.msi
  tags:
  - Install
  - Repair

- name: Install putty
  win_package:
    path: C:\tmp\putty.msi
    product_id: PuTTY
  tags:
  - Install
  - Repair

- name: Uninstall putty
  win_package:
    path: C:\tmp\putty.msi
    state: absent
  tags:
  - Uninstall
