---
# tasks file for putty

- name: Copying Installation file from share location for Putty
  win_copy:
    src : '/home/ec2-user/files/putty-64bit-0.76-installer.msi'
    dest: 'C:\tmp\putty.msi'
  tags:
  - Install
  - Repair


- name: Install putty
  win_package:
    path: 'C:\tmp\putty.msi'
    product_id: 'PuTTY'
    state: present
  tags:
  - Install
  - Repair

- name: Uninstall putty
  win_package:
    path: 'C:\tmp\putty.msi'
    state: absent
  tags:
  - Uninstall


- name: Cleaning up files copied from share location
  win_file:
    path: 'C:\tmp\putty.msi'
    state: absent
  tags:
  - Uninstall
