---
# tasks file for Winzip

- name: Download WinZip
  win_get_url:
    url: https://download.winzip.com/winzip250-64.msi
    dest: C:\tmp\winzip.msi
  tags:
  - Install
  - Repair

- name: Install WinZip
  win_package:
    path: C:\tmp\winzip.msi
    product_id: WinZip
  tags:
  - Install
  - Repair

- name: Uninstall WinZip
  win_package:
    path: C:\tmp\winzip.msi
    state: absent
  tags:
  - Uninstall

